### ISSUE TITLE
asyncio imports need SyntaxError

### ISSUE THREAD

**Issue by meejah** [tavendo/txaio#5] opened 2015-07-31 19:08 UTC
See https://github.com/tavendo/AutobahnPython/issues/434

If you have Python 2.7.8 and trollius installed, the ``import asyncio`` in txaio which is guarded by ``except ImportError`` will actually throw a ``SyntaxError`` also/instead. (Tried with Python 2.7.8 on Debian)

**Comment by oberstet** [comment] 2015-08-06 12:21
can't reproduce:

```console
oberstet@corei7ub1310:~$ ./python278/bin/python 
Python 2.7.8 (default, Aug  6 2015, 14:12:00) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named asyncio
>>> import trollius
>>> 
```

and 

```console
oberstet@corei7ub1310:~$ ./python278/bin/python 
Python 2.7.8 (default, Aug  6 2015, 14:12:00) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from autobahn.asyncio.websocket import WebSocketClientProtocol, WebSocketClientFactory
>>> import autobahn
>>> autobahn.__version__
'0.10.4'
>>> 
```

**Comment by oberstet** [comment] 2015-08-06 12:23
the problems comes from installing the `asyncio` package rather than `trollius`:

```console
oberstet@corei7ub1310:~$ ./python278/bin/pip install asyncio
Collecting asyncio
/home/oberstet/python278/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading asyncio-3.4.3.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 1.4MB/s 
Building wheels for collected packages: asyncio
  Running setup.py bdist_wheel for asyncio
  Stored in directory: /home/oberstet/.cache/pip/wheels/3f/6c/58/eabf8f5b223390a1a99ee7f76e342357bccc6d0a619f82ffdc
Successfully built asyncio
Installing collected packages: asyncio
Successfully installed asyncio-3.4.3
oberstet@corei7ub1310:~$ ./python278/bin/python 
Python 2.7.8 (default, Aug  6 2015, 14:12:00) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import txaio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oberstet/python278/lib/python2.7/site-packages/txaio/__init__.py", line 103, in <module>
    from txaio.aio import *  # noqa
  File "/home/oberstet/python278/lib/python2.7/site-packages/txaio/aio.py", line 37, in <module>
    import asyncio
  File "/home/oberstet/python278/lib/python2.7/site-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/home/oberstet/python278/lib/python2.7/site-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
>>> 
```

**Comment by oberstet** [comment] 2015-08-06 12:25
closing as invalid

**Closed by oberstet** 2015-08-06 12:25 UTC
